### PR TITLE
updated akka-extensions dependency

### PR DESCRIPTION
**Pull request by antonkulaga**
обновил зависимости и чуть-чуть подправил билд

[Review on Reviewable](https://reviewable.io/reviews/denigma/drugage/6)

### CODE REVIEW

**Comment by rmihael** [comment]
Reviewed 17 of 18 files at r1.
Review status: 17 of 18 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[.travis.yml, line 12 [r1]](https://reviewable.io:443/reviews/denigma/drugage/6#-Jty_W4Hv21iaDheg_d4)** ([raw file](https://github.com/denigma/drugage/blob/a14c51c4e4c969237344fcae31446f44253e4286/.travis.yml#L12)):</sup>
Чего решил убрать? Мешает?

---

<sup>**[.travis.yml, line 18 [r1]](https://reviewable.io:443/reviews/denigma/drugage/6#-Jty_ZpBwpwRFcoGciHz)** ([raw file](https://github.com/denigma/drugage/blob/02d315a7c1d89b7c6d211e05a3211c789e6a8430/.travis.yml#L18)):</sup>
Ух ты, оно и так умеет :)

---

<sup>**[backend/src/main/scala/org/denigma/drugage/routes/Registration.scala, line 44 [r1]](https://reviewable.io:443/reviews/denigma/drugage/6#-JtyaDX3FAG-64FWIA1W)** ([raw file](https://github.com/denigma/drugage/blob/02d315a7c1d89b7c6d211e05a3211c789e6a8430/backend/src/main/scala/org/denigma/drugage/routes/Registration.scala#L44)):</sup>
Как-то не аккуратно смотрится хардкод имени куки тут. Логично было бы сделать действие logout по аналогии с login.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/drugage/6)

**Comment by rmihael** [comment]
Reviewed 1 of 18 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/drugage/6)

**Comment by antonkulaga** [comment]
<sup>**[.travis.yml, line 12 [r1]](https://reviewable.io:443/reviews/denigma/drugage/6#-Jty_W4Hv21iaDheg_d4)** ([raw file](https://github.com/denigma/drugage/blob/a14c51c4e4c969237344fcae31446f44253e4286/.travis.yml#L12)):</sup>
Я просто закопипастил конфиг трависа с проекта, где он работает нормально=) Там трабл с компиляцией был сугубо по вине трависа просто

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/drugage/6)

**Comment by antonkulaga** [comment]
<sup>**[.travis.yml, line 18 [r1]](https://reviewable.io:443/reviews/denigma/drugage/6#-Jty_ZpBwpwRFcoGciHz)** ([raw file](https://github.com/denigma/drugage/blob/02d315a7c1d89b7c6d211e05a3211c789e6a8430/.travis.yml#L18)):</sup>
скорее задел на будущее, чтобы попробовать селениум тесты запускать

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/drugage/6)

**Comment by antonkulaga** [comment]
<sup>**[backend/src/main/scala/org/denigma/drugage/routes/Registration.scala, line 44 [r1]](https://reviewable.io:443/reviews/denigma/drugage/6#-JtyaDX3FAG-64FWIA1W)** ([raw file](https://github.com/denigma/drugage/blob/02d315a7c1d89b7c6d211e05a3211c789e6a8430/backend/src/main/scala/org/denigma/drugage/routes/Registration.scala#L44)):</sup>
давай пока пусть так побудет, а потом я в akka-http-extensions добавлю именную директиву логаута и тогда поменяем.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/denigma/drugage/6)

**Pull request merged**
